Fix b/29451090 adding validation and tests for timeout parameters
googlegsa/library pull request #25
Opened 2017-04-07 08:37 UTC by mpaggi

Adding code and tests to check the values of the following properties:
adaptor.docContentTimeoutSecs
adaptor.docHeaderTimeoutSecs
adaptor.heartbeatTimeoutSecs
In case the value set in config file is invalid, default value is returned and a warning is logged.

2017-04-07 18:01 UTC, PapaJoltOmega reviewed
Thank you

2017-04-07 18:01 UTC, pjogooglecom commented on src/com/google/enterprise/adaptor/Config.java
> +      boolean allowNeg, boolean allowEmpty) {
Why do we have these last two booleans if they are always passed in false?

2017-04-07 18:01 UTC, pjogooglecom commented on src/com/google/enterprise/adaptor/Config.java
> +    // For invalid value, returning default
Why do we decide to continue with default rather than die?

2017-04-07 18:48 UTC, BrettMichaelJohnson requested changes

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +      if ((null == secondsAsString) || "0".equals(secondsAsString) ||
Config.getValue() does not return null.

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +          return Long.parseLong(secondsAsString) * 1000;
The pedantic mission-to-mars programmer would ensure that multiplying by 1000 will not overflow.

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +    return validateTimeout("adaptor.docHeaderTimeoutSecs", "30", false, false);
You are restating the default values supplied in the constructor here. I don't like that for 2 reasons:  
1) If the defaults are changed in the future, the change may be missed here.  
2) The default value may have been overridden by the connector using overrideKey(). (The FS adaptor overrides these values)

One solution might be to pull the default values from defaultConfig, but you need to be wary of nulls and computed values (not the case for these).

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
>      return Long.parseLong(getValue("adaptor.incrementalPollPeriodSecs")) * 1000;
you might as well validate this one too.

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/ConfigTest.java
> +      assertEquals(Long.parseLong("30000"),
Consider using TimeUnit.SECONDS.toMillis(30).

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +                           false, false);
The default value of heartbeatTimeoutSecs is "", so allowEmpty should probably be true. But that will still generate a WARNING in the logs.

2017-04-07 18:48 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/ConfigTest.java
> +
Add tests that verify that valid timeout config values are returned.

2017-04-07 19:05 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +          return Long.parseLong(secondsAsString) * 1000;
In fact, I would probably have passed in min and max allowed values (which also does away with allowNeg, which is never true anyway).

2017-04-07 19:11 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +    // For invalid value, returning default
I agree with PJ.  For truly invalid values, throw InvalidConfigurationException.  This also avoids the problems with the defaults below. Although the heartbeatTimeout will still have to fall back to headerTimeout gracefully.

2017-04-17 23:02 UTC, BrettMichaelJohnson commented
Michele, we are planning a release of the adaptor library this week.  Please consider finishing this up so that is may be included.

2017-04-18 20:13 UTC, pjogooglecom commented
Michele, would you mind if Brett took this CL over? Thank you

2017-04-19 12:22 UTC, mpaggi commented
Sorry I did not have time to work on this before. Here the changes suggested.
I changed also the tests since 'thrown.expect' does not seems to works in a for cycle.
No problem for me if Brett wants to take over this CL.

2017-04-19 18:03 UTC, BrettMichaelJohnson requested changes

2017-04-19 18:03 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Config.java
> +    if ("adaptor.heartbeatTimeoutSecs".equalsIgnoreCase(property) &&
This belongs in getAdaptorHeartbeatTimeoutMillis, not here.

2017-04-19 18:03 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/ConfigTest.java
> +                                      Long.toString(Long.MAX_VALUE + 1)};
Long.MAX_VALUE + 1 = Long.MIN_VALUE
What you want is (Long.MAX_VALUE/1000)+1 , which will overflow when converted to milliseconds.

2017-04-19 18:03 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/ConfigTest.java
> +                               + "adaptor.heartbeatTimeoutSecs=\n");
In this test, explicitly set heartbeat, then add another test that verifies the fallback value.

2017-04-19 18:46 UTC, BrettMichaelJohnson commented
PJ,
I took over this CL, and made (admittedly my own) suggested changes.
Please review.

2017-04-19 22:58 UTC, PapaJoltOmega approved these changes
LGTM.  Thank you

2017-04-19 22:58 UTC, pjogooglecom commented on src/com/google/enterprise/adaptor/Config.java
> +            + property + ". Only a numeric value is accepted.");
Can we say numeric that also conveys integer?

2017-04-19 23:12 UTC, BrettMichaelJohnson approved these changes

2017-04-19 23:13 UTC, merged