Allow connectors to add params for use by MetadataTransforms
googlegsa/library pull request #33
Opened 2017-04-18 23:20 UTC by BrettMichaelJohnson

This change allows the connector to insert metadata associated
with the document into the params that MetadataTransforms
receive. This data may be useful to the transforms, but
will not be sent to the GSA.

2017-04-27 23:43 UTC, wiarlawd reviewed
I don't see the utility of this. You don't eliminate the risk of name collisions, you just risk them with the library instead of the repository. Is there something you could do with this that you can't do by creating and deleting a metadata element for the same purpose?

John L

2017-04-28 00:08 UTC, wiarlawd requested changes
I missed this as the underpinning for stickiness until I read the other CL.

John L

2017-04-28 00:08 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/Response.java
> +  public void addParam(String key, String value);
Just for the record, this has the same problem that the added pushGroupDefinitions overload has, breaking source compatibility with unit tests.

As the basis for stickiness, I would much prefer a setTransmissionDecision or setDoNotSkip method, rather than opening the door to adding random params that the library may or may not care about. I think the library should validate the params that are passable here, if you want to retain the generic method. You also can't overwrite existing library params with the current code, but that isn't documented here.

2017-04-28 00:08 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +        if (!Strings.isNullOrEmpty(du)) {
Why is this changing here?

2017-04-28 00:08 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/WrapperAdaptor.java
> +      return params;
Return a copy? I know this is just "like the others", but what's it for?

2017-04-28 00:08 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/CommandStreamParser.java
> +        case PARAM_NAME:
Did you actually try running whatever this is?

2017-04-28 00:51 UTC, BrettMichaelJohnson commented
As an example of why this is useful, the Filesystem adaptor wants to do this:

    // Add the rest of the file attributes into the params for use by           
    // MetadataTransforms.                                                      
    resp.addParam("Creation-Date", dateFormatter.get().format(
        new Date(attrs.creationTime().toMillis())));
    resp.addParam("Last-Modified-Date", dateFormatter.get().format(
        new Date(attrs.lastModifiedTime().toMillis())));
    resp.addParam("Last-Access-Date", dateFormatter.get().format(
        new Date(attrs.lastAccessTime().toMillis())));
    resp.addParam("Is-Directory", Boolean.toString(attrs.isDirectory()));
    resp.addParam("Is-Regular-File", Boolean.toString(attrs.isRegularFile()));
    if (attrs.isRegularFile()) {
      rep.addParam("File-Size", Long.toString(attrs.size()));
    }

This make the BasicFileAttributes available to the transforms for decision
and/or copying into metadata to be indexed.  For instance the dates may
be used by the DateFilter (deprecating the internal one).  And original 
file size is b/18996895.

2017-04-28 01:08 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +        if (!Strings.isNullOrEmpty(du)) {
I honestly cannot remember why I thought this was needed.

2017-04-28 01:08 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/CommandStreamParser.java
> +        case PARAM_NAME:
I ran its test.

2017-04-28 01:08 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/WrapperAdaptor.java
> +      return params;
This class should be marked VisibleForTesting.  It is used by CommandStreamParserTest and others that use TestHelper.  Basically the getters allow the tests to extract fields from the Response.

2017-04-28 01:33 UTC, wiarlawd commented
I'm just barely buying the argument about metadata that might be useful to transforms, but which the connector does not want to decide to index on its own. Access date is the classic example.

What about allowing extended param names only with "X-" prefixes, to avoid collisions?

It's a little weird that addParam (maybe putParam, since it's a map and multiple values are not supported?) is a duplicate of setLock, setDisplayUrl, etc., but that Forced-Transmission-Decision requires you to use addParam.

2017-04-28 01:52 UTC, BrettMichaelJohnson commented
I was thinking of strongly suggested namespaces for the params, i.e. FS_LAST_ACCESS_DATE.
I can accept the dichotomy between params that get sent to the GSA (lock, displayUrl, etc) and params that are used by the filters.  Adding a transmissionDecision/sticky setter to the response wouldn't be too terrible, but I really see it as six-of-a-half-dozen.

2017-04-29 01:04 UTC, wiarlawd commented
I don't see a need for a per-connector type namespace, the scope here is just one connector instance. But I would prefer an enforced namespace.

If we keep addParam for Forced-Transmission-Decision, then I think we should choose between adding setForcedTransmissionDecision, too, which weakens addParam as a feature, or deprecating setDisplayUrl, setLock, et al. (if there are others).

2017-05-07 04:28 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +        if (!Strings.isNullOrEmpty(du)) {
It's not your code, but it just prevents us from reparsing the URL if it was changed by the transform pipeline. Seems harmless enough and not worth changing.

2017-05-07 04:39 UTC, wiarlawd commented
Just as a reminder, to myself as much as anyone, Brett and I had an offline chat about namespaces, and agreed to require an X- prefix for names not matching library keys. In fact, I would go as far as adding setForcedTransmissionDecision to the other CL (the alternative being to deprecate the other existing setters), and having the generic addParam method flat require the X- prefix, that is, you could not set the predefined library keys with this method. That also means that this CL is not a prerequisite to #37, but an independent feature, justified mainly by access time (and some other odd metadata where indexing doesn't make much sense but filtering does).

2017-05-07 05:09 UTC, wiarlawd commented
Please add a test that at least calls addParam, maybe something like adding access time with a filter that skips the document?

2017-05-07 05:10 UTC, wiarlawd requested changes

2017-05-07 05:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +
Delete blank line.

2017-05-07 05:10 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +    public void addParam(String key, String value) {
I would go with putParam (collection semantics) or setParam (generic meaning), rather than addParam, which suggests multiple values are possible.

2017-05-07 20:32 UTC, wiarlawd commented
This change has javadoc errors in {@link MetadataTransforms} in two files.

2017-05-13 01:34 UTC, wiarlawd approved these changes
LGTM, with a nit.

Please wait for PJ to review.

2017-05-13 01:34 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/DocumentHandlerTest.java
> +    MetadataTransformPipeline transform = new MetadataTransformPipeline(transforms,
80 cols

2017-05-15 21:12 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +    public void addParam(String key, String value) {
I choose setParam()

2017-05-15 21:12 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +
Done.

2017-05-15 21:12 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/DocumentHandler.java
> +        if (!Strings.isNullOrEmpty(du)) {
Restored.

2017-05-15 21:12 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/Response.java
> +  public void addParam(String key, String value);
I enforced the param key must start with "X-"

2017-05-18 00:40 UTC, PapaJoltOmega reviewed
To sum up the review thread:
- This feature is for allowing someone to filter on acces time and other values that change more frequently than indexed metadata
- This feature is no longer being made to support sticky transform decision

Yes?

Thank you

2017-05-18 21:01 UTC, BrettMichaelJohnson commented
PJ,
Yes. We chose another method of setting the sticky transform decision.

2017-05-18 23:57 UTC, PapaJoltOmega approved these changes

2017-05-18 23:59 UTC, merged