Replace Corpora with Keyset - Part1
googlegsa/library pull request #43
Opened 2017-05-06 01:34 UTC by BrettMichaelJohnson

2017-05-07 06:36 UTC, wiarlawd reviewed
Wordsmithing and java doc.

John L

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  /** Keys for data stored in the {@code Map} of {@code params}. */
Change to a // or /* comment, since this would be completely misleading to read in javadoc.

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     key=Display-URL
Leaving out the *'s is unnecessary and possibly incorrect.

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +    public static Keyset from(String val) {
Add javadoc and a throws tag for IllegalArgumentException, and do the same for Transmission-Decision. The enum values could stand some javadoc, too. There is no mention in the javadoc of what the string names for the enum values actually are. Don't forget that you can add javadoc to the individual values of the enum as well (e.g., METADATA and PARAMS).

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * Suppose a transform wishes examine or modify the display URL, which is
s/wishes/wishes to/

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * stored in the {@code params}. The transform's configuration might look
s/look like/include/

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +      return (val == null) ? METADATA : Keyset.valueOf(val.toUpperCase());
Add US locale.

2017-05-07 06:36 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +    @Override
Add javadoc for these, too, just to say that they return the names.

2017-05-09 02:03 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  /** Keys for data stored in the {@code Map} of {@code params}. */
Added JavaDoc for each key.

2017-05-09 02:03 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * Suppose a transform wishes examine or modify the display URL, which is
Done.

2017-05-09 02:03 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * stored in the {@code params}. The transform's configuration might look
include

2017-05-10 00:25 UTC, wiarlawd requested changes

2017-05-10 00:25 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * If unspecified, the default value is {@code METADATA}.
I don't like this change, since in this context, it's the name that matters, not the enum identifier.

2017-05-10 00:25 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  /** The key for the document's last modified timestamp supplied in the
This is a style guide violation. Implementation comments can be formatted like this, but not javadoc.

https://google.github.io/styleguide/javaguide.html#s7.1-javadoc-formatting

2017-05-10 00:25 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     *  This value's name is {code as-is}.
Missing @'s on these.

2017-05-10 18:51 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  /** The key for the document's last modified timestamp supplied in the
Done.

2017-05-10 18:51 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     *  This value's name is {code as-is}.
Done.

2017-05-11 02:30 UTC, PapaJoltOmega reviewed
Is the plan to allow skip document filter to use name corpora and name keyset or just one?

Why not make a CL that changes how SkipDocumentFilter works, rather than this detached structure?

Thank you

2017-05-11 06:28 UTC, wiarlawd commented
Brett and I have been talking about SkipDocumentFilter. Since we dropped support for "metadata or params", it can't be rewritten as a small wrapper on RegexFilter, which was designed to replace it. We weren't sure whether it made sense to leave it alone (and be certain of not breaking something) or add keyset as a small nod to consistency. None of the existing pull requests are addressing SkipDocumentFilter and corpora vs keyset.

This change is actually part of adding Keyset to the other transforms. Temporally, this isn't part 1 at all, but part 2:

Part 1: Add keyset to RegexFilter (in place of corpora), DateFilter (in place of corpora), and PrebuiltTransforms (new)
Part 2: Add a shared Keyset enum to MetadataTransform (this CL)
Part 3: Edit the transforms to use the shared Keyset.

It's a funny order, but most of the coding in part 1 had been finished before the renaming decision was made, so parts 2 and 3 were not part of the original plan, and the filters all had their own nested Corpora enum originally.

2017-05-11 06:35 UTC, wiarlawd requested changes
Nits

2017-05-11 06:35 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * If unspecified, the default value is {@code METADATA}.
Missed this? s/METADATA/metadata/

2017-05-11 06:35 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     key=Display-URL
Add *'s

2017-05-11 06:35 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +    /** The key/value(s) reside in the {@link Metadata}.
Add line breaks for javadoc formatting in these two.

2017-05-11 20:35 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     key=Display-URL
Done.

2017-05-11 20:35 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * @since 4.1.4
Add // @since TODO(bmj)

2017-05-11 20:35 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * @since 4.1.4
Done.

2017-05-11 20:35 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +    /** The key/value(s) reside in the {@link Metadata}.
Done.

2017-05-11 20:35 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * If unspecified, the default value is {@code METADATA}.
I thought this over, and METADATA is correct as the value of the enum.

2017-05-12 02:50 UTC, wiarlawd requested changes
Sorry, I was looking at the javadoc over the metadata vs METADATA issue.

2017-05-12 02:50 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  // @since TODO(bmj)
Belay that order.

2017-05-12 02:50 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     */
javadoc is warning about a missing return tag.

2017-05-12 02:50 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     */
javadoc is warning about a missing return tag.

2017-05-12 02:50 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * supplied to the {@link #transform} method of a {@code MetadataTransform}.
link here, but code for TransmissionDecision. Also, most of the time for a method link, you want to specify the text: s/#transform/#transform transform/

2017-05-12 02:50 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * If unspecified, the default value is {@code METADATA}.
I'll buy that.

2017-05-18 00:58 UTC, pjogooglecom commented
> been talking about SkipDocumentFilter. Since we dropped 
> support for "metadata or params", it can't be rewritten as a 
> small wrapper on RegexFilter, which was designed to replace 
> it. We weren't sure whether it made sense to leave it alone 
> (and be certain of not breaking something) or add keyset as 
> a small nod to consistency. None of the existing pull requests 
> are addressing SkipDocumentFilter and corpora vs keyset.

What do you want to do? 

Do you want to change SkipDocumentFilter in backwards incompatible way?

or do we want to add metadata_and_params while making default be metadata?

I would like if we would revist this CL after checking in some of the items that will use it.  That way the code is used when it is submitted. 

Thank you

2017-05-18 08:19 UTC, wiarlawd commented
I don't have a super-strong preference for whether to add keyset to SkipDocumentFilter. I would lean slightly toward adding it for consistency. That would be a separate change. We do not want to break backward compatibility of existing transform configs, or add METADATA_OR_PARAMS to Keyset (because it's prone to hard to understand failures and doesn't add new functionality, beyond slightly simplifying transforms on the params by not having to specify the keyset).

So what you want here is to combine this change with Brett's planned part 3, to introduce Keyset in MetadataTransform and remove it from the individual transforms in one change? Seems reasonable to me either way. Brett was just trying to create smaller, incremental changes.

2017-05-18 17:31 UTC, pjogooglecom commented
(1) Do we want to deprecate SkipDocumentFilter?

(2) I would prefer to read the combined part 2+3.

Instead of breaking CLs into:
CL 1: make pieces
CL 2: use pieces

I think there are advantages to:
CL 1: make part of the pieces and use those pieces
CL 2: make another part of the pieces and use those pieces

(Let me know if that's not clear)

http://googlegsa.github.io/adaptor/docs/DevelopmentProperties.html -- It's the preference for vertical slices and eschewing horizontal slices. Even here where I thinK i know where we are going I would like to combine part 2+3, please.

Thank you very much

2017-05-18 20:36 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +   * supplied to the {@link #transform} method of a {@code MetadataTransform}.
Done.

2017-05-18 20:36 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     */
Done.

2017-05-18 20:36 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +     */
Done.

2017-05-18 20:38 UTC, BrettMichaelJohnson commented
PJ, I would rather have done this as one CL, but split it up to avoid merge conflicts with all the other outstanding CLs.

2017-05-18 20:56 UTC, PapaJoltOmega approved these changes
Makes sense to avoid merge.  Thank you.  LGTM.

2017-05-18 23:26 UTC, wiarlawd approved these changes
LGTM, with a nit.

2017-05-18 23:26 UTC, wiarlawd commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  // @since TODO(bmj)
You can remove this TODO.

2017-05-19 00:05 UTC, BrettMichaelJohnson commented on src/com/google/enterprise/adaptor/MetadataTransform.java
> +  // @since TODO(bmj)
Done.

2017-05-19 00:07 UTC, merged