Dissolved most of WrapperAdaptor.
googlegsa/library pull request #48
Opened 2017-05-09 01:06 UTC by wiarlawd

Most of WrapperAdaptor was unused. Its reason for existence was
AutoUnzip, which was deleted 4 years ago in commit 85c51d5.

WrapperAdaptor: Used trivially by StatRpcMethodTest, replaced by Proxy
WrapperRequest: Unused
WrapperResponse: Unused
GetContentsRequest: Unused
GetContentsResponse: Moved to the testing package in #46
WrapperDocIdPusher: Unused
WrapperAdaptorContext: Used trivially by TestHelper and 3 connectors

WrapperAdaptorContext is left here for backward compatibility
with existing connectors, but may be replaced later.

2017-05-10 18:32 UTC, BrettMichaelJohnson requested changes

2017-05-10 18:32 UTC, BrettMichaelJohnson commented on test/com/google/enterprise/adaptor/TestHelper.java
> -  public static byte[] getDocContent(Adaptor adaptor, DocId docId)
TestHelper is public and so is this method, so they are both available to connectors. I don't think you should remove this method.

2017-05-11 00:55 UTC, PapaJoltOmega reviewed
Thank you

2017-05-11 00:55 UTC, pjogooglecom commented on test/com/google/enterprise/adaptor/TestHelper.java
> +  public static <T> T newProxyInstance(Class<T> clazz) {
how about:
   s/newProxyInstance/doNothingMock/

2017-05-11 00:55 UTC, pjogooglecom commented on test/com/google/enterprise/adaptor/TestHelper.java
> +  /** Gets a proxy for the given class that does nothing. */
s/that does nothing/where every method is a no-op/

2017-05-11 01:14 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/TestHelper.java
> +  public static <T> T newProxyInstance(Class<T> clazz) {
Would you accept doNothingProxy? I'd like to keep Proxy in the names of things that use Proxy.

2017-05-11 01:14 UTC, wiarlawd commented on test/com/google/enterprise/adaptor/TestHelper.java
> -  public static byte[] getDocContent(Adaptor adaptor, DocId docId)
None of our connectors use the test classes from the library. They all reference the library through adaptor-withlib.jar. Four connectors have copies of TestHelper, but none of them use this one, or anything out of WrapperAdaptor except for WrapperAdaptorContext as noted. If third-party connectors are referring to things in the library tests, I have no sympathy.

2017-05-18 01:19 UTC, PapaJoltOmega approved these changes
Thanks for ameliorating code debt. LGTM

2017-05-18 01:19 UTC, pjogooglecom commented on test/com/google/enterprise/adaptor/TestHelper.java
> -  public static byte[] getDocContent(Adaptor adaptor, DocId docId)
Thanks for the consideration.  

Agree with John that reaching into test subdir is tacit agreement to higher level of disruption.

2017-05-19 00:16 UTC, PapaJoltOmega approved these changes
LGTM

2017-05-19 06:28 UTC, BrettMichaelJohnson approved these changes
LGTM

2017-05-19 08:13 UTC, closed without merging